# This config file only for develop

baseURL = "https://www.manikandaraj.com/themes/mango/"
# title = "Mango - A Simple theme for Hugo!"
enableRobotsTXT = true
enableEmoji = true

mainSections = ["post"]

hasCJKLanguage = true     # has chinese/japanese/korean ?

[pagination]
  pagerSize = 5

rssLimit = 20             # Limit Entry Count to Rss file
disqusShortname = "manikandaraj"      # disqus_shortname
googleAnalytics = "G-4SFSR6JRVT"      # G-********
copyright = ""            # default: params.author.name
enableGitInfo = true # use git commit log to generate lastmod record 
# uglyURLs = true

# language support en / zh-cn / other... translations present in i18n/
defaultContentLanguage = "en"  # Default language to use (if you setup multilingual support)
[languages]
[languages.en]
  title = "Mango - A Simple theme for Hugo!"
  languageName = "English"
  weight = 1
[languages.zh-cn]
  title = "Mango —— 一个简洁的 Hugo 主题"
  languageName = "中文"
  weight = 2

[[languages.en.menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  pageref = "/"

#[[languages.en.menu.main]]
#  name = "Docs"
#  weight = 11
#  identifier = "docs"
#  pageref = "/categories/docs/"

#[[languages.en.menu.main]]
#  name = "Demo"
#  weight = 12
#  identifier = "demo"
#  pageref = "/categories/demo/"

# docs submenu
#[[languages.en.menu.main]]
#  name = "Markdown Syntax"
#  weight = 12
#  parent = "docs"
#  url = "/post/markdown-syntax/"

[[languages.en.menu.main]]
  name = "Archives"
  weight = 20
  identifier = "archives"
  pageref = "/post/"
[[languages.en.menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  pageref = "/tags/"
[[languages.en.menu.main]]
  name = "external-link"
  weight = 50
  url = "https://gohugo.io"



[sitemap]                 # essential                     # 必需
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"


[params]
  debug = false             # If true, load `eruda.min.js`. See https://github.com/liriliri/eruda
  since = "2025"            # Site creation time
  homeFullContent = false   # if false, show post summaries on home page. Otherwise show full content.
  rssFullContent = true     # if false, Rss feed instead of the summary

  author.name = "manikandaraj"      # essential
  author.url = "/about"        # optional

  # site info (optional)                                  
  logoTitle = "Mani S"        # default: the title value
  keywords = ["Hugo", "theme","mango"]
  description = "My Matrix - Manikandaraj Srinivasan!"

  # paginate of archives, tags and categories
  archive-paginate = 10

  # paginate style, default use numbered pagination links
  # if true, use original "Previous" and "Next" links.
  # paginateOriginalStyle = true

  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "2006-01-02"

  # show word count and read time
  moreMeta = false

  # show language chooser in menu
  showMenuLanguageChooser = true

  # Some global options, you can also close or open something in front matter for a single post, see more information from `archetypes/default.md`.
  toc = true
  photoswipe = true         # see https://github.com/dimsemenov/PhotoSwipe
  bootcdn = false           # In china. @Deprecated: use [params.publicCDN]
  mathjax = false           # see https://www.mathjax.org/

  contentCopyright = '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'

  changyanAppid = ""        # Changyan app id
  changyanAppkey = ""       # Changyan app key
  tencent_analytics = ""    # Tencent Analytics
  baidu_push = false        # baidu push
  baidu_analytics = ""      # Baidu Analytics
  baidu_verification = ""   # Baidu Verification
  google_verification = ""  # Google_Verification

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  customCSS = []            # if ['custom.css'], load '/static/css/custom.css' file
  customJS = []             # if ['custom.js'], load '/static/js/custom.js' file


  [params.publicCDN]        # load these files from public cdn
    enable = false

  [params.utteranc]         # utteranc is a comment system based on GitHub issues. see https://utteranc.es
    enable = false
    repo = "manikandaraj/comments-in-mango"    # The repo to store comments
    issueTerm = "pathname"
    theme = "github-dark"                           # theme: github-light, github-dark, github-dark-orange, icy-dark, dark-blue, photon-dark

  [params.giscus]         # giscus is a comment system based on GitHub Discussions. see https://giscus.app
    enable = true
    repo = "manikandaraj/comments-in-mango"
    repoId = "MDEwOlJlcG9zaXRvcnkxNDAyNDYzNjc="
    category = "Announcements"
    categoryId = "DIC_kwDOCFv9X84CRRWF"
    # mapping = "pathname"  # comment value is the default value
    # strict = 0
    # reactionsEnabled = 1
    # emitMetadata = 0
    # inputPosition = "top"
    # theme = "light"
    # lang = "en"
    # lazyLoading = false

  [params.search.google]    # google custom search, see https://cse.google.com
    enable = true
    id = "002186711602136249422:q1gkomof_em"
    title = "Search"

  # use public git repo url to link lastmod git commit, enableGitInfo should be true.
  [params.gitInfo]
    gitRepo = "https://github.com/manikandaraj/mango"
    showCommitMessage = true

  [params.reward]
    enable = false
    wechat = "/path/to/your/wechat-qr-code.png"
    alipay = "/path/to/your/alipay-qr-code.png"

  [params.social]
    a-email = "mailto:your@email.com"
    b-stackoverflow = "http://localhost:1313/1"
    c-twitter = "http://localhost:1313/2"
    d-facebook = "http://localhost:1313/3"
    e-linkedin = "http://localhost:1313"
    f-google = "http://localhost:1313"
    g-github = "http://localhost:1313"
    h-weibo = "http://localhost:1313"
    i-zhihu = "http://localhost:1313"
    j-douban = "http://localhost:1313"
    k-pocket = "http://localhost:1313"
    l-tumblr = "http://localhost:1313"
    m-instagram = "http://localhost:1313"
    n-gitlab = "http://localhost:1313"
    o-goodreads = "http://localhost:1313"
    p-coding = "http://localhost:1313"
    q-bilibili = "http://localhost:1313"
    r-codeforces = "http://localhost:1313"
    s-mastodon = "http://localhost:1313"
    t-youtube = "http://localhost:1313"
    u-twitch = "http://localhost:1313"

# Highlight options. See https://gohugo.io/content-management/syntax-highlighting/
[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'friendly'
    tabWidth = 4
